---
version: "3"
services:
#  admin-server:
#    image: as
#    networks:
#      - springboot-db-net
#    ports:
#      - 1111:1111

  eureka-server:
    image: es
    networks:
      - springboot-db-net
    ports:
      - 8761:8761
  ap-api :
    image: ar-api
    networks:
      - springboot-db-net
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
      - eureka-server
#      - admin-server
    environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#  dc-api :
#    image: dc-api
#    networks:
#      - springboot-db-net
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mysqldb
#      - eureka-server
##      - admin-server
#    environment:
#     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
     
#  ed-api :
#    image: ed-api
#    networks:
#      - springboot-db-net
#    ports:
#      - "8083:8083"
#    depends_on:
#      - mysqldb
#      - eureka-server
##      - admin-server
#    environment:
#     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
     
#  co-api :
#    image: co-api
#    networks:
#      - springboot-db-net
#    ports:
#      - "8084:8084"
#    depends_on:
#      - mysqldb
#      - eureka-server
##      - admin-server
#    environment:
#     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arapidb
networks:
  springboot-db-net:
...